// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChS_xbxCuQLn7BpXROtelpq90wlpt1iLs',
    appId: '1:149599160117:web:8a97d71be90c80629dae7c',
    messagingSenderId: '149599160117',
    projectId: 'alexandria-a1c2b',
    authDomain: 'alexandria-a1c2b.firebaseapp.com',
    storageBucket: 'alexandria-a1c2b.appspot.com',
    measurementId: 'G-NGVF9GS5LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyLQz4ODoEfZaI4TCApIC3xQVym30J_DQ',
    appId: '1:149599160117:android:33f46569ec6652239dae7c',
    messagingSenderId: '149599160117',
    projectId: 'alexandria-a1c2b',
    storageBucket: 'alexandria-a1c2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoy5Mzt89uonvN6EEgOWRkLzo3blUJ39s',
    appId: '1:149599160117:ios:2e53aa9340fcee369dae7c',
    messagingSenderId: '149599160117',
    projectId: 'alexandria-a1c2b',
    storageBucket: 'alexandria-a1c2b.appspot.com',
    iosClientId:
        '149599160117-ua1htisv8qos8h6bmkkupkscgsrtaish.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3Appforbooks',
  );
}
